### ISSUE TITLE
"Charset mismatch" when running the standalone version under Ubuntu

### ISSUE THREAD

**Issue by jzell** [HeidelTime/heideltime#17]
```
I have previously used HeidelTime's standalone version on Mac OSX and on a Lubuntu machine
without any problem. 
Today I tried it on Ubuntu (running as VirtualBox) and can't get rid of this mistake:


usr@usr-VirtualBox:~/Downloads/Temporal_Annotation_Initial/Standalone$ java -jar de.unihd.dbs.heideltime.standalone.initial.jar
/home/usr/Temporal_Annotation/lill_sample.txt -l german
Error: Unable to access jarfile de.unihd.dbs.heideltime.standalone.initial.jar
usr@usr-VirtualBox:~/Downloads/Temporal_Annotation_Initial/Standalone$ java -jar de.unihd.dbs.heideltime.standalone.jar
/home/usr/Temporal_Annotation/lill_sample.txt -l german
java.lang.RuntimeException: Opps! Could not find token fï¿½rbringen in JCas after tokenizing
with TreeTagger. Hmm, there may exist a charset missmatch! Default encoding is UTF-8
and should always be UTF-8 (use -Dfile.encoding=UTF-8). If input document is not UTF-8
use -e option to set it according to the input, additionally.
	at de.unihd.dbs.uima.annotator.treetagger.TreeTaggerWrapper.tokenize(TreeTaggerWrapper.java:262)
	at de.unihd.dbs.uima.annotator.treetagger.TreeTaggerWrapper.process(TreeTaggerWrapper.java:221)
	at de.unihd.dbs.heideltime.standalone.components.impl.TreeTaggerWrapper.process(TreeTaggerWrapper.java:43)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.establishPartOfSpeechInformation(HeidelTimeStandalone.java:388)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.establishHeidelTimePreconditions(HeidelTimeStandalone.java:336)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:481)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:430)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.main(HeidelTimeStandalone.java:728)
<?xml version="1.0"?>
<!DOCTYPE TimeML SYSTEM "TimeML.dtd">
<TimeML>

178. Frondienst der Wurmsbacher Lehenleute 
1605 <TIMEX3 tid="t4" type="DATE" value="XXXX-06-06">Juni 6</TIMEX3>. Rapperswil 
Uf fürbringen unnd clagen der frawen äbbtißin unnd convent des würdigen gozhuß Wurmbspach
gegen und wider jre lehenlüthen zu Wagen, jm Buech und in der Auw: Das dieselbigen
vermeinen, die wyl die fraw andere jres gozhuß güetter verlichen, also dz sy keiner
acherlüthen nit mer mangelbar und aber so sy die behallten, jnnen die ächer zebuwen
12 tag schuldig und sonnsten nit.
</TimeML>

It annotates the first occurance of a temporal expression, and then stops... 
My input files are in UTF8:

usr@usr-VirtualBox:~/Temporal_Annotation$ file lill_sample.txt 
lill_sample.txt: UTF-8 Unicode text, with very long lines

I also tried to indicate -Dfile.encoding=UTF-8, as the error message says, but it doesn't
help a bit...


```

Original issue reported on code.google.com by `natako88` on 2014-07-28 14:27:00

**Comment by jzell** [comment]
imported issue, closing.
