### ISSUE TITLE
java.lang.NullPointerException error for standalone version

### ISSUE THREAD

**Issue by EnsarEmirali** [HeidelTime/heideltime#88]
Hi,
I am newbie for Java. I completed the installation by following Manual.pdf file. Then I created an example text file on the same folder with standalone. When I run "java -jar de.unihd.dbs.heideltime.standalone.jar ex.txt" command on terminal, I get following error:
```
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Properties.put(Properties.java:1334)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.establishPartOfSpeechInformation(HeidelTimeStandalone.java:404)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.establishHeidelTimePreconditions(HeidelTimeStandalone.java:332)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:516)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.process(HeidelTimeStandalone.java:465)
	at de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone.main(HeidelTimeStandalone.java:782)
Oct 12, 2021 10:30:56 PM de.unihd.dbs.heideltime.standalone.HeidelTimeStandalone process
WARNING: Processing aborted due to errors
<?xml version="1.0"?>
<!DOCTYPE TimeML SYSTEM "TimeML.dtd">
<TimeML>
This year we gonna go to the village.
</TimeML>
```
How can I solve this problem?

Thanks for your help.
Best regards,

**Comment by dharmenpunjani** [comment]
Hello I was having same issue and had same set of error.
The problem is that I commented the line "chineseTokenizerPath = SET ME IN CONFIG.PROPS! (e.g., /home/jannik/treetagger/chinese-tokenizer)" inside config.props.
So if you have commented it kindly remove the comment and it should work.
All the best !
